<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIOOKesu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIOOKesu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIOOKesu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIOOKesu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIOOKesu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IOOKesu',
    'container.build_id' => 'c763805f',
    'container.build_time' => 1589240740,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIOOKesu');
